# Generated by Django 4.1.2 on 2022-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_parking_contact_remove_parking_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="id",
        ),
        migrations.AddField(
            model_name="parking",
            name="vehicle_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
